spring:
  data:
    mongodb:
      uri: "mongodb+srv://${DB_USERNAME:username}:${DB_PASSWORD:password}@cluster0.lhkyq3i.mongodb.net/${DB_NAME:db-name}?retryWrites=true&w=majority"

server:
  port: 80
  servlet:
    context-path: /

logging:
  level:
    root: info
    org.springframework.web: info
  logback:
    rollingpolicy:
      max-history: 7
  file:
    name: "./logs/crypto.log"

jwt:
  secret: "4_WwR3LEUgLb*R2db49Aj7AzppZWLPiovsdfnlkg3edcLJBGVR#&BVP9eqne123fsdghtew5"
  expirationInMs: 1800000
